# Generated by Django 3.0.4 on 2020-03-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_photo_gallery',
            name='description',
            field=models.CharField(default='edit this description', max_length=500),
        ),
    ]
