# Generated by Django 3.0.4 on 2020-03-20 05:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogues', '0002_school_photo_gallery_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School_events_january',
            new_name='School_events',
        ),
        migrations.RemoveField(
            model_name='school_events_august',
            name='author',
        ),
        migrations.RemoveField(
            model_name='school_events_december',
            name='author',
        ),
        migrations.RemoveField(
            model_name='school_events_february',
            name='author',
        ),
        migrations.RemoveField(
            model_name='school_events_july',
            name='author',
        ),
        migrations.RemoveField(
            model_name='school_events_june',
            name='author',
        ),
        migrations.RemoveField(
            model_name='school_events_march',
            name='author',
        ),
        migrations.RemoveField(
            model_name='school_events_may',
            name='author',
        ),
        migrations.RemoveField(
            model_name='school_events_november',
            name='author',
        ),
        migrations.RemoveField(
            model_name='school_events_october',
            name='author',
        ),
        migrations.RemoveField(
            model_name='school_events_september',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='school_events',
            options={'verbose_name': 'school event', 'verbose_name_plural': 'school events'},
        ),
        migrations.DeleteModel(
            name='School_events_april',
        ),
        migrations.DeleteModel(
            name='School_events_august',
        ),
        migrations.DeleteModel(
            name='School_events_december',
        ),
        migrations.DeleteModel(
            name='School_events_february',
        ),
        migrations.DeleteModel(
            name='School_events_july',
        ),
        migrations.DeleteModel(
            name='School_events_june',
        ),
        migrations.DeleteModel(
            name='School_events_march',
        ),
        migrations.DeleteModel(
            name='School_events_may',
        ),
        migrations.DeleteModel(
            name='School_events_november',
        ),
        migrations.DeleteModel(
            name='School_events_october',
        ),
        migrations.DeleteModel(
            name='School_events_september',
        ),
    ]
