# Generated by Django 3.0.4 on 2020-03-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0004_auto_20200320_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_anthem',
            old_name='stanza_five',
            new_name='stanza',
        ),
        migrations.RemoveField(
            model_name='school_anthem',
            name='stanza_four',
        ),
        migrations.RemoveField(
            model_name='school_anthem',
            name='stanza_one',
        ),
        migrations.RemoveField(
            model_name='school_anthem',
            name='stanza_six',
        ),
        migrations.RemoveField(
            model_name='school_anthem',
            name='stanza_three',
        ),
        migrations.RemoveField(
            model_name='school_anthem',
            name='stanza_two',
        ),
    ]
