# Generated by Django 3.0.4 on 2020-04-26 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogues', '0007_school_warriors_way'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_previous_heads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_head', models.CharField(max_length=200)),
                ('start_year', models.CharField(max_length=200)),
                ('end_year', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'school Previous Head',
                'verbose_name_plural': 'school Previous Heads',
            },
        ),
    ]
