# Generated by Django 3.0.4 on 2020-04-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0008_school_previous_heads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_previous_heads',
            options={'verbose_name': 'school Previous Heads', 'verbose_name_plural': 'school Previous Heads'},
        ),
    ]
